apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-persistent-volume
  labels:
    type: local
    namespace: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv0001/